
services:
  web:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: alacenapp_front
    ports:
      - "8080:8080"
    volumes:
      - ./Front:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: alacenapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alacenapp
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
